version: 2.1

jobs:
  build-image:
    docker:
      - image: cimg/base:current
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            export PYTHON_VERSION=$(cat .python-version)
            docker image build --build-arg "python_version=${PYTHON_VERSION}" --tag kelvintaywl/test-splitting-debugger:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - run:
          name: Publish to Docker Hub
          command: |
            docker image push kelvintaywl/test-splitting-debugger:latest

workflows:
  on-commit:
    jobs:
      - build-image
